# Generated by Django 5.2.5 on 2026-07-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('faculty', 'Faculty'), ('dean', 'Dean'), ('student', 'Student')], default='student', max_length=10),
        ),
    ]
