# Generated by Django 5.2.5 on 2026-07-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_meetingattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rating_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
